config/routes.rb
Serienshare::Application.routes.draw do

  resources :tvshows, :only => [:index, :new, :create, :destroy] do
    resources :episodes, :only => [:index]
  end
  root :to => 'tvshows#index'

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :tvshow
  attr_accessible :epnum, :seasonnum, :title, :prodnum, :airdate, :link

  validates :epnum, :uniqueness => { :scope => :tvshow_id, :message => "Episoden-Nr. sind eindeutig innerhalb der Serie." }
end

app/models/tvrage.rb
require 'httparty'

class Tvrage
  include HTTParty
  base_uri 'services.tvrage.com'
  format :xml

  def self.find_by_title(  title )
    h = get('/feeds/search.php?show=' + CGI.escape( title ));
    h = h["Results"]["show"]

    unless Array === h
      h = [ h ]
    end 

    h

  end

  def self.episodes( showid )
    h = get('/feeds/episode_list.php?sid=' + showid.to_s );

    arr = []

    return [] if h["Show"].nil?
    return [] if h["Show"]["Episodelist"].nil?
    return [] unless Array === h["Show"]["Episodelist"]["Season"]

    h["Show"]["Episodelist"]["Season"].each do |season|
      unless season["episode"].nil?
        if  Array === season["episode"] 
          season["episode"].each do |episode|
            e = episode.clone
            e["epnum"] = e["epnum"].to_i
            e["seasonnum"] = season["no"].to_i
            arr.push( e )
          end
        end
      end
    end

    arr
  end
end

app/models/tvshow.rb
# encoding: utf-8

class Tvshow < ActiveRecord::Base

  has_many :episodes, :dependent => :destroy
  attr_accessible :showid, :name, :link, :prodnum, :seasons, :country, :started, :ended, :status, :classification
  accepts_nested_attributes_for :episodes

  validates :showid,  :uniqueness => {  :message => "Diese Serie ist bereits vorhanden" } 
  validates :link,    :format => { :with => /^http:..www.tvrage.com./, :message => "Link zu TVRage muss bleiben" }
  validates :country, :format => { :with => /^\w\w$/,  :message => "Zwei-Buchtstaben Code für das Land" }
  validates :started, :format => { :with => /^\d{4}$/, :message => "Jahrezahl mit 4 Ziffern - oder leer" }, :allow_blank => true
  validates :ended,   :format => { :with => /^\d{4}$/, :message => "Jahrezahl mit 4 Ziffern - oder leer" }, :allow_blank => true


  protected

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_filter :get_tvshow

  def index
    @episodes = @tvshow.episodes
  end


private 
  def get_tvshow
    @tvshow = Tvshow.find(params[:tvshow_id])
    raise "Show not found" if @tvshow.nil?
  end
end

app/controllers/tvshows_controller.rb
class TvshowsController < ApplicationController
  def index
    @tvshows = Tvshow.all
  end

  # GET /tvshows/new                 - ohne parameter 'title' - ist das nomale formular
  # GET /tvshows/new?title=Sherlock  - nur ein suchfeld: sucht erst bei tvrage und erzeugt dann
  #                                    das normale formular
  def new
    @tvshow = Tvshow.new

    unless params[:title].blank?
      tvrage = Tvrage.find_by_title( params[:title] )
      gon.shows = tvrage.index_by{|s| s["showid"] }
    end

    if tvrage.nil? 
      render "new"
    else 
      @tvrage_options = tvrage.map{|s|[s["name"],s["showid"]]}
      render "new_with_data"
    end
  end

  # POST /tvshows
  def create
    @tvshow = Tvshow.new(params[:tvshow])

    unless @tvshow.save
      render "new_with_data"
      return
    end

    Tvrage.episodes( @tvshow.showid ).each do |ep|
      Rails.logger.warn("Episoden-Daten: #{ep}")
      @tvshow.episodes.create( ep )
    end

    redirect_to tvshow_episodes_path(@tvshow), notice: 'Serie wurde erfolgreich gespeichert'
  end

  # DELETE /tvshows/1
  def destroy
    @tvshow = Tvshow.find(params[:id])
    @tvshow.destroy

    redirect_to tvshows_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/episodes/index.html.erb
<h1><%= @tvshow.name %></h1>
<p>
<%= link_to 'Zurück zu den Serien', tvshows_path %>
</p>

<% @episodes.each do |episode| %>
    Season <%= episode.seasonnum %>
    Episode <%= episode.epnum %>: 
    <b><%= link_to episode.title, episode.link %></b>. 
  <br>
<% end %>

<p>
<%= link_to 'Zurück zu den Serien', tvshows_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Serienshare</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tvshows/index.html.erb
<h1>Fernsehserien verwalten</h1>

<p>
<%= link_to 'New TV-Show', new_tvshow_path %>
</p>

<dl>
<% @tvshows.each do |tvshow| %>
  <dt><b><%= link_to tvshow.name, tvshow_episodes_path( tvshow ) %> </b>
      |  <%= link_to 'Destroy', tvshow, method: :delete, data: { confirm: 'Are you sure?' } %></dt>
  <dd>  <%= tvshow.country %>, <%= tvshow.started %> bis 
    <% if tvshow.ended.blank? %> ... <% else %> <%= tvshow.ended %>  <% end %> (<%= tvshow.seasons %> Seasons). <%= tvshow.status %>.
  </dd>
<% end %>

<p>
<%= link_to 'New TV-Show', new_tvshow_path %>
</p>

app/views/tvshows/new.html.erb
<h1>New tvshow</h1>

<%= form_for(@tvshow, :url => new_tvshow_path(), :method => :get ) do |f| %>
  <% if @tvshow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tvshow.errors.count, "error") %> prohibited this tvshow from being saved:</h2>

      <ul>
      <% @tvshow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag "Suche nach dem Titel" %><br />
    <%= text_field_tag :title %>
  </div>

  <div class="actions">
    <%= f.submit :value => "Suche"  %>
  </div>
<% end %>
<%= link_to 'Back', tvshows_path %>

app/views/tvshows/new_with_data.html.erb
<h1>New Tvshow as found on TVRage</h1>

<%= form_for(@tvshow) do |f| %>
  <% if @tvshow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tvshow.errors.count, "error") %> Fehler, die Serie kann so nicht gespeichert werden:</h2>

      <ul>
      <% @tvshow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @tvrage_options %>

    <div class="field">
      <%= f.label :showid %><br />
      <%= f.select(:showid, options_for_select( @tvrage_options ),  {:prompt => 'Serie auswählen'})  %>
    </div>

  <% else %>

    <div class="field">
      <%= f.label :showid %><br />
      <%= f.text_field :showid %>
    </div>

  <% end %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :prodnum %><br />
    <%= f.text_field :prodnum %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :seasons %><br />
    <%= f.number_field :seasons %>
  </div>
  <div class="field">
    <%= f.label :started %><br />
    <%= f.text_field :started %>
  </div>
  <div class="field">
    <%= f.label :ended %><br />
    <%= f.text_field :ended %>
  </div>
  <div class="field">
    <%= f.label :classification %><br />
    <%= f.text_field :classification %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit :value => "Diese Serie - und ihre Folgen - abspeichern"  %>
  </div>
<% end %>
<%= link_to 'Back', tvshows_path %>